version: "3.7"
services:
  server:
    build: .
    image: labflow/swabseq-analysis-server:latest
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - PROPAGATE_EXCEPTIONS=True
      - "SERVER_NAME=${SERVER_NAME}"
      - "AUTH_PROVIDER=${AUTH_PROVIDER}"
      - "AUTH0_DOMAIN=${AUTH0_DOMAIN}"
      - "AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}"
      - "AUTH0_AUTHORIZATION_URL=${AUTH0_AUTHORIZATION_URL}"
      - "AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}"
      - "AUTH0_TOKEN_URL=${AUTH0_TOKEN_URL}"
    ports:
      - 5000:5000
